// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/udstream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_DoubleValue
	//	*Value_FloatValue
	//	*Value_Int64Value
	//	*Value_Uint64Value
	//	*Value_BoolValue
	//	*Value_StringValue
	//	*Value_BytesValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_udstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_udstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_udstream_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*Value_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Value) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Value) GetUint64Value() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Value_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,2,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,4,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*Value_DoubleValue) isValue_Value() {}

func (*Value_FloatValue) isValue_Value() {}

func (*Value_Int64Value) isValue_Value() {}

func (*Value_Uint64Value) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_StringValue) isValue_Value() {}

func (*Value_BytesValue) isValue_Value() {}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   uint64                 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	SourceId      uint32                 `protobuf:"varint,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_udstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_udstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_udstream_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Message) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Message) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Message) GetSourceId() uint32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type DeltaBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint32                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaBatch) Reset() {
	*x = DeltaBatch{}
	mi := &file_proto_udstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaBatch) ProtoMessage() {}

func (x *DeltaBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_udstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaBatch.ProtoReflect.Descriptor instead.
func (*DeltaBatch) Descriptor() ([]byte, []int) {
	return file_proto_udstream_proto_rawDescGZIP(), []int{2}
}

func (x *DeltaBatch) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DeltaBatch) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type FullSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceId      uint32                 `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Nodes         []*Message             `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullSnapshot) Reset() {
	*x = FullSnapshot{}
	mi := &file_proto_udstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSnapshot) ProtoMessage() {}

func (x *FullSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_udstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSnapshot.ProtoReflect.Descriptor instead.
func (*FullSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_udstream_proto_rawDescGZIP(), []int{3}
}

func (x *FullSnapshot) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FullSnapshot) GetSourceId() uint32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *FullSnapshot) GetNodes() []*Message {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Packet_Delta
	//	*Packet_Full
	Payload       isPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_proto_udstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_udstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_proto_udstream_proto_rawDescGZIP(), []int{4}
}

func (x *Packet) GetPayload() isPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetDelta() *DeltaBatch {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *Packet) GetFull() *FullSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Full); ok {
			return x.Full
		}
	}
	return nil
}

type isPacket_Payload interface {
	isPacket_Payload()
}

type Packet_Delta struct {
	Delta *DeltaBatch `protobuf:"bytes,1,opt,name=delta,proto3,oneof"`
}

type Packet_Full struct {
	Full *FullSnapshot `protobuf:"bytes,2,opt,name=full,proto3,oneof"`
}

func (*Packet_Delta) isPacket_Payload() {}

func (*Packet_Full) isPacket_Payload() {}

var File_proto_udstream_proto protoreflect.FileDescriptor

const file_proto_udstream_proto_rawDesc = "" +
	"\n" +
	"\x14proto/udstream.proto\x12\budstream\"\x89\x02\n" +
	"\x05Value\x12#\n" +
	"\fdouble_value\x18\x01 \x01(\x01H\x00R\vdoubleValue\x12!\n" +
	"\vfloat_value\x18\x02 \x01(\x02H\x00R\n" +
	"floatValue\x12!\n" +
	"\vint64_value\x18\x03 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fuint64_value\x18\x04 \x01(\x04H\x00R\vuint64Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fstring_value\x18\x06 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\a \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\x89\x01\n" +
	"\aMessage\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12%\n" +
	"\x05value\x18\x03 \x01(\v2\x0f.udstream.ValueR\x05value\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\rR\bsourceId\"M\n" +
	"\n" +
	"DeltaBatch\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12-\n" +
	"\bmessages\x18\x02 \x03(\v2\x11.udstream.MessageR\bmessages\"r\n" +
	"\fFullSnapshot\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\rR\bsourceId\x12'\n" +
	"\x05nodes\x18\x03 \x03(\v2\x11.udstream.MessageR\x05nodes\"o\n" +
	"\x06Packet\x12,\n" +
	"\x05delta\x18\x01 \x01(\v2\x14.udstream.DeltaBatchH\x00R\x05delta\x12,\n" +
	"\x04full\x18\x02 \x01(\v2\x16.udstream.FullSnapshotH\x00R\x04fullB\t\n" +
	"\apayloadB\x15Z\x13udproto/proto/pb;pbb\x06proto3"

var (
	file_proto_udstream_proto_rawDescOnce sync.Once
	file_proto_udstream_proto_rawDescData []byte
)

func file_proto_udstream_proto_rawDescGZIP() []byte {
	file_proto_udstream_proto_rawDescOnce.Do(func() {
		file_proto_udstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_udstream_proto_rawDesc), len(file_proto_udstream_proto_rawDesc)))
	})
	return file_proto_udstream_proto_rawDescData
}

var file_proto_udstream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_udstream_proto_goTypes = []any{
	(*Value)(nil),        // 0: udstream.Value
	(*Message)(nil),      // 1: udstream.Message
	(*DeltaBatch)(nil),   // 2: udstream.DeltaBatch
	(*FullSnapshot)(nil), // 3: udstream.FullSnapshot
	(*Packet)(nil),       // 4: udstream.Packet
}
var file_proto_udstream_proto_depIdxs = []int32{
	0, // 0: udstream.Message.value:type_name -> udstream.Value
	1, // 1: udstream.DeltaBatch.messages:type_name -> udstream.Message
	1, // 2: udstream.FullSnapshot.nodes:type_name -> udstream.Message
	2, // 3: udstream.Packet.delta:type_name -> udstream.DeltaBatch
	3, // 4: udstream.Packet.full:type_name -> udstream.FullSnapshot
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_udstream_proto_init() }
func file_proto_udstream_proto_init() {
	if File_proto_udstream_proto != nil {
		return
	}
	file_proto_udstream_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_DoubleValue)(nil),
		(*Value_FloatValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_Uint64Value)(nil),
		(*Value_BoolValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BytesValue)(nil),
	}
	file_proto_udstream_proto_msgTypes[4].OneofWrappers = []any{
		(*Packet_Delta)(nil),
		(*Packet_Full)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_udstream_proto_rawDesc), len(file_proto_udstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_udstream_proto_goTypes,
		DependencyIndexes: file_proto_udstream_proto_depIdxs,
		MessageInfos:      file_proto_udstream_proto_msgTypes,
	}.Build()
	File_proto_udstream_proto = out.File
	file_proto_udstream_proto_goTypes = nil
	file_proto_udstream_proto_depIdxs = nil
}
